//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFRK_Element_Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class FFRK_Data
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Iteration { get; set; }
        public string Type { get; set; }
        public string ElementType { get; set; }
        public string EnElement { get; set; }
        public string SBType { get; set; }
        public string Level99 { get; set; }
        public string Dived { get; set; }
        public string ExtraInfo { get; set; }
    }
}
